version: '3.7'
services:
  
  mysql:
    container_name: mysql-container
    ports:
      - 3308:3306
    image: mysql:8.0.28
    networks:
      - microservice-network
    volumes:
      - new-volume:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: ABC@1234 
       MYSQL_DATABASE: sholl
  
  redis: 
    image: redis:7.2.0
    container_name: redis-db
    ports:
      - 6000:6379
    volumes:
      - new-volume:/data
    networks:
      - microservice-network
  
  user-service:
    container_name: user_container
    ports:
      - 1000:1000
    depends_on:
      - mysql
      - redis
    build: 
      context: ./service_user/
      dockerfile: Dockerfile
    networks:
      - microservice-network
    environment:
      REDIS_LINK: redis
      MYSQL_PASSWORD: ABC@1234
      MYSQL_DATABASE: scholl 
      MYSQL_USER: root 
      MYSQL_HOST: mysql 
      PORT: 1000
networks:
  microservice-network:
    external: true
volumes:
  new-volume: 
    external: true

      